spring.application.name=cliniva
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cliniva}
spring.datasource.username=${SPRING_DATASOURCE_USER:cliniva}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:cliniva}

# schema gerenciado 100% pelo Flyway (validate apenas confere as colunas)
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true